### ISSUE TITLE
[run failed]

### ISSUE THREAD

**Issue by aguaiyoung** [gamemann/XDP-Forwarding#1]
hi,gamemann
i test in my env ,but it's failed,can you help me? my os kenel is too low?
[root@centos7_6 XDP-Forwarding]# ./xdpfwd
libbpf: load bpf program failed: Invalid argument
libbpf: -- BEGIN DUMP LOG ---
libbpf:
back-edge from insn 584 to 594

libbpf: -- END LOG --
libbpf: failed to load program 'xdp_prog'
libbpf: failed to load object '/etc/xdpfwd/xdp_prog.o'
Error loading XDP program. File => /etc/xdpfwd/xdp_prog.o. Error => Unknown error 4007. Error Number-> -4007
[root@centos7_6 XDP-Forwarding]# uname -a
Linux centos7_6 4.14.105-19-0018-2-gfcc70b0 #1 SMP Fri Dec 18 09:09:19 CST 2020 x86_64 x86_64 x86_64GNU/Linux

**Comment by gamemann** [comment]
Hey and yes. While loop [support](https://lwn.net/Articles/794934/) was added in 5.3 and above which is required for this XDP program. Therefore, you'll need kernel 5.3 or above at the minimum.

**Comment by aguaiyoung** [comment]
> Hey and yes. While loop [support](https://lwn.net/Articles/794934/) was added in 5.3 and above which is required for this XDP program. Therefore, you'll need kernel 5.3 or above at the minimum.

thanks a lot.
